# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 866998bdb60ef2031b88c90bbab5b04fd6b72d3b74fd8039fac0d5ad527a79589c0fd83bf5c7bb21d2c652c40e7c0c8dac9be0699ef0210643cf6fc0893a4be2

test:
  secret_key_base: 8f607c1c4049eef914aa1cfa72368878bbdd0242962dc0f924c021323b38c49b2fc4d6f9738e409c0738d5aa179274df0c783ee58be068f5ee09ec4d3b73a605

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
